name = "sandeep-ramgolam-nuxt3"
compatibility_date = "2024-09-22"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm build"
cwd = ""
watch_dir = ""

[env.production]
# Production environment variables can be set here

# Cloudflare Pages configuration
pages_build_output_dir = ".output/public"
